baseurl = "https://tanzsport.github.io/esv-json-schema"
languageCode = "de-de"
title = "ESV JSON Schema"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
    # General information
    author = ""
    description = ""
    copyright = ""

    # Repository
    # provider = "GitHub"
    # repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

    version = ""
    logo = ""
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = ['css/validator/validator.css']
    custom_js  = ['js/validator/validator.js']

    # Syntax highlighting theme
    highlight_css  = ""

[params.palette]
    primary = "blue"
    accent  = "cyan"

[params.font]
    text = "Open Sans"
    code = "Ubuntu Mono"

[social]
    twitter = ""
    github  = "tanzsport"
    email   = ""

[[menu.main]]
    name   = "Übersicht"
    url    = "/"
    weight = 1

[[menu.main]]
    name   = "Online-Validierung"
    url    = "validator"
    weight = 2

[blackfriday]
    smartypants	= true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
